"""Shared scaffolding for endpoint-backed YouTube MCP tools."""

from mcp_server.tools.youtube_common.activities import (
    ACTIVITIES_LIST_INPUT_SCHEMA,
    ACTIVITIES_LIST_TOOL_NAME,
    ActivitiesListToolError,
    build_activities_list_contract,
    build_activities_list_handler,
    build_activities_list_tool_descriptor,
    map_activities_list_result,
    validate_activities_list_arguments,
)
from mcp_server.tools.youtube_common.captions import (
    CAPTIONS_INSERT_INPUT_SCHEMA,
    CAPTIONS_INSERT_TOOL_NAME,
    CAPTIONS_LIST_INPUT_SCHEMA,
    CAPTIONS_LIST_TOOL_NAME,
    CaptionsInsertToolError,
    CaptionsListToolError,
    build_captions_insert_contract,
    build_captions_insert_handler,
    build_captions_insert_tool_descriptor,
    build_captions_list_contract,
    build_captions_list_handler,
    build_captions_list_tool_descriptor,
    map_captions_insert_result,
    map_captions_list_result,
    validate_captions_insert_arguments,
    validate_captions_list_arguments,
)
from mcp_server.tools.youtube_common.contracts import (
    AuthMode,
    AvailabilityState,
    validate_safe_public_metadata,
    YouTubeToolContract,
    YouTubeToolContractError,
    derive_tool_name,
)
from mcp_server.tools.youtube_common.conventions import (
    ErrorCategory,
    InputConvention,
    ResponseBoundary,
    ResponseBoundaryKind,
    ResponseConvention,
    ResponseKind,
    sanitize_error_details,
)
from mcp_server.tools.youtube_common.examples import REPRESENTATIVE_YOUTUBE_TOOL_CONTRACTS
from mcp_server.tools.youtube_common.families import (
    REQUIRED_YOUTUBE_RESOURCE_FAMILIES,
    RESOURCE_FAMILY_REGISTRY,
    SHARED_YOUTUBE_HELPER_BOUNDARY,
    YouTubeResourceFamily,
    build_representative_tool_descriptor,
    get_resource_family,
)

__all__ = [
    "AuthMode",
    "AvailabilityState",
    "ACTIVITIES_LIST_INPUT_SCHEMA",
    "ACTIVITIES_LIST_TOOL_NAME",
    "CAPTIONS_INSERT_INPUT_SCHEMA",
    "CAPTIONS_INSERT_TOOL_NAME",
    "CAPTIONS_LIST_INPUT_SCHEMA",
    "CAPTIONS_LIST_TOOL_NAME",
    "ActivitiesListToolError",
    "CaptionsInsertToolError",
    "CaptionsListToolError",
    "ErrorCategory",
    "InputConvention",
    "YouTubeToolContractError",
    "YouTubeResourceFamily",
    "YouTubeToolContract",
    "REPRESENTATIVE_YOUTUBE_TOOL_CONTRACTS",
    "REQUIRED_YOUTUBE_RESOURCE_FAMILIES",
    "RESOURCE_FAMILY_REGISTRY",
    "ResponseBoundary",
    "ResponseBoundaryKind",
    "ResponseConvention",
    "ResponseKind",
    "SHARED_YOUTUBE_HELPER_BOUNDARY",
    "build_activities_list_contract",
    "build_activities_list_handler",
    "build_activities_list_tool_descriptor",
    "build_captions_insert_contract",
    "build_captions_insert_handler",
    "build_captions_insert_tool_descriptor",
    "build_captions_list_contract",
    "build_captions_list_handler",
    "build_captions_list_tool_descriptor",
    "build_representative_tool_descriptor",
    "derive_tool_name",
    "get_resource_family",
    "map_activities_list_result",
    "map_captions_insert_result",
    "map_captions_list_result",
    "sanitize_error_details",
    "validate_safe_public_metadata",
    "validate_activities_list_arguments",
    "validate_captions_insert_arguments",
    "validate_captions_list_arguments",
]
